name: forex
description: Forex_Trading_App.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_remote_config: ^4.2.7
  firebase_analytics: ^10.5.1
  webview_flutter: ^4.4.1
  path_provider: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: SF pro
      fonts:
        - asset: assets/fonts/sf-pro-display-cufonfonts/SFPRODISPLAYBLACKITALIC.OTF
          weight: 900
          style: italic
        - asset: assets/fonts/sf-pro-display-cufonfonts/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: assets/fonts/sf-pro-display-cufonfonts/SFPRODISPLAYHEAVYITALIC.OTF
          weight: 400
          style: italic
        - asset: assets/fonts/sf-pro-display-cufonfonts/SFPRODISPLAYLIGHTITALIC.OTF
          style: italic
          weight: 300
        - asset: assets/fonts/sf-pro-display-cufonfonts/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/sf-pro-display-cufonfonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/sf-pro-display-cufonfonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
          style: italic
          weight: 600
        - asset: assets/fonts/sf-pro-display-cufonfonts/SFPRODISPLAYTHINITALIC.OTF
          style: italic
        - asset: assets/fonts/sf-pro-display-cufonfonts/SFPRODISPLAYULTRALIGHTITALIC.OTF
          style: italic
          weight: 300
    - family: Unbounded
      fonts:
        - asset: assets/fonts/Unbounded/static/Unbounded-Black.ttf
        - asset: assets/fonts/Unbounded/static/Unbounded-Bold.ttf
          weight: 700
        - asset: assets/fonts/Unbounded/static/Unbounded-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Unbounded/static/Unbounded-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Unbounded/static/Unbounded-Light.ttf
          weight: 300
        - asset: assets/fonts/Unbounded/static/Unbounded-Medium.ttf
          weight: 500
        - asset: assets/fonts/Unbounded/static/Unbounded-Regular.ttf
        - asset: assets/fonts/Unbounded/static/Unbounded-SemiBold.ttf
          weight: 400
