// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmh_xANpi37vrifVHNedgSbHkY5UKYtyY',
    appId: '1:1075203913779:web:667f387944ea13791b0b46',
    messagingSenderId: '1075203913779',
    projectId: 'forex-trading-app-faded',
    authDomain: 'forex-trading-app-faded.firebaseapp.com',
    storageBucket: 'forex-trading-app-faded.appspot.com',
    measurementId: 'G-WCV2FM25KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOOBW9bKzBrhiJJ_KbRByA9xiE6OfmqtQ',
    appId: '1:1075203913779:android:4608f030cf63786a1b0b46',
    messagingSenderId: '1075203913779',
    projectId: 'forex-trading-app-faded',
    storageBucket: 'forex-trading-app-faded.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYBcaCdqv4cVRcl6MO_lOn3T4Gs_NyuZM',
    appId: '1:1075203913779:ios:3e0f7b6479821dae1b0b46',
    messagingSenderId: '1075203913779',
    projectId: 'forex-trading-app-faded',
    storageBucket: 'forex-trading-app-faded.appspot.com',
    iosBundleId: 'com.example.forex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYBcaCdqv4cVRcl6MO_lOn3T4Gs_NyuZM',
    appId: '1:1075203913779:ios:9d0da8b132b14f951b0b46',
    messagingSenderId: '1075203913779',
    projectId: 'forex-trading-app-faded',
    storageBucket: 'forex-trading-app-faded.appspot.com',
    iosBundleId: 'com.example.forex.RunnerTests',
  );
}
